### ISSUE TITLE
Javascript bug in the interactive poem

### ISSUE THREAD

**Issue by zmughal** [oh-uhouston-3/oh-uhouston-3.github.io#2]
Expected behavior:  It should go back to the beginning of the poem when you click the last line.

Actual behavior:  It says "undefined" and then gets stuck there.

I think the problem is in poem.js.  Can somebody fix this?

**Comment by vandersmissenc** [comment]
I'm going to work on this issue.

**Comment by rawrspace** [comment]
The issue was that when the function was called with a number greater than the length of the array it was causing an undefined error. I added a line to use modulo on the number that was passed to the function which keeps it in the bounds. Resolved in #9
